### ISSUE TITLE
DynamoDev-StarterKit-v1.1.2.zip doesn't include the latest dist

### ISSUE THREAD

**Issue by StudioLE** [alvpickmans/Dynamo-Dev-Starter-Kit#3]
The download asset `DynamoDev-StarterKit-v1.1.2.zip` in [GitHub releases](https://github.com/alvpickmans/Dynamo-Dev-Starter-Kit/releases/tag/v1.1.2) doesn't contain the latest files from `Dynamo-Dev-Starter-Kit\dist` therefore isn't updated to support Visual Studio 2019.

Best solution will likely be to create a new release v1.1.3 ensuring the correct files are zipped.

**Comment by alvpickmans** [comment]
This should be fixed on release 1.1.3 https://github.com/alvpickmans/Dynamo-Dev-Starter-Kit/releases/tag/1.1.3

Feel free to open this issue again if it doesn't work!
